import type { Vector3 } from "three";
import type { Entity } from "../entities";
import type { EnumFacing } from "../math/facing";
import type { World } from "../world";

// Base Item class
export class Item {
	name: string;
	maxStackSize: number;
	maxDamage: number;
	hasSubtypes: boolean;

	getUnlocalizedName(): string;
	getItemStackDisplayName(stack: ItemStack): string;
	onItemUse(
		stack: ItemStack,
		player: Entity,
		world: World,
		pos: Vector3,
		side: EnumFacing,
		hitX: number,
		hitY: number,
		hitZ: number,
	): boolean;
	onItemRightClick(stack: ItemStack, world: World, player: Entity): ItemStack;
	getMaxItemUseDuration(stack: ItemStack): number;
	getItemUseAction(stack: ItemStack): string;
	onPlayerStoppedUsing(
		stack: ItemStack,
		world: World,
		player: Entity,
		timeLeft: number,
	): void;
	hitEntity(stack: ItemStack, target: Entity, attacker: Entity): boolean;
	onBlockDestroyed(
		stack: ItemStack,
		world: World,
		block: Block,
		pos: Vector3,
		player: Entity,
	): boolean;
	canHarvestBlock(block: Block): boolean;
	getStrVsBlock(stack: ItemStack, block: Block): number;
}

// ItemBlock - Placeable blocks
export class ItemBlock extends Item {
	block: Block;
	getBlock(): Block;
	placeBlockAt(
		stack: ItemStack,
		player: Entity,
		world: World,
		pos: Vector3,
		side: EnumFacing,
		hitX: number,
		hitY: number,
		hitZ: number,
		metadata: number,
	): boolean;
}

// ItemSword - Swords
export class ItemSword extends Item {
	attackDamage: number;
	weaponMaterial: string;
	getAttackDamage(): number;
}

// ItemBow - Bows
export class ItemBow extends Item {
	maxItemUseDuration: number;
}

export class ItemArmor extends Item {
	armorType: number;
	/** **IMPORTANT**: USE DUMPS OR AUTO REMAP PROXY */
	damageReduceAmount: number;
	maxDamage: number;
	renderIndex: number;
	material: string;

	getArmorMaterial(): string;
	getColor(stack: ItemStack): number;
	removeColor(stack: ItemStack): void;
	hasColor(stack: ItemStack): boolean;
}

export class ItemFood extends Item {
	healAmount: number;
	saturationModifier: number;
	isWolfsFavoriteMeat: boolean;
	alwaysEdible: boolean;

	getHealAmount(stack: ItemStack): number;
	getSaturationModifier(stack: ItemStack): number;
}

export class ItemTool extends Item {
	efficiencyOnProperMaterial: number;
	damageVsEntity: number;
	toolMaterial: string;

	getToolMaterial(): string;
	getStrVsBlock(stack: ItemStack, block: Block): number;
}

export class ItemPickaxe extends ItemTool {}

export class ItemAppleGold extends ItemFood {}

export interface EnchantmentData {
	id: number;
	lvl: number;
}

export class ItemStack {
	item: Item;
	stackSize: number;
	maxStackSize: number;
	itemDamage: number;

	getItem(): Item;
	getDisplayName(): string;
	getEnchantmentTagList(): EnchantmentData[] | null;
	hasEffect(): boolean;
	isItemEnchanted(): boolean;
	isItemEnchantable(): boolean;
	getMaxStackSize(): number;
	isStackable(): boolean;
	isItemDamaged(): boolean;
	getItemDamage(): number;
	getMaxDamage(): number;
	attemptDamageItem(amount: number, random: unknown): boolean;
	damageItem(amount: number, entity: Entity): void;
	hitEntity(target: Entity, player: Entity): void;
	onBlockDestroyed(
		world: World,
		block: Block,
		pos: unknown,
		player: Entity,
	): void;
	canHarvestBlock(block: Block): boolean;
	interactWithEntity(player: Entity, target: Entity): boolean;
	clone(): ItemStack;
	areItemStackTagsEqual(other: ItemStack): boolean;
	areItemStacksEqual(other: ItemStack): boolean;
	isItemEqual(other: ItemStack): boolean;
	getTooltip(player: Entity, advanced: boolean): string[];
	hasDisplayName(): boolean;
	setStackDisplayName(name: string): ItemStack;
	clearCustomName(): void;
	hasTagCompound(): boolean;
	// TODO: idk what types these are, assuming strings?
	getTagCompound(): string;
	setTagCompound(nbt: string): void;
	splitStack(by: number): ItemStack;
}

// Global Items registry
export declare const Items: {
	readonly emerald_sword: Item;
	readonly diamond_sword: ItemSword;
	readonly iron_sword: ItemSword;
	readonly stone_sword: ItemSword;
	readonly wooden_sword: ItemSword;
	readonly bow: ItemBow;
	readonly arrow: Item;
	readonly golden_apple: ItemAppleGold;
	readonly apple: ItemFood;
	readonly bread: ItemFood;
	readonly cooked_beef: ItemFood;
	readonly cooked_porkchop: ItemFood;
	readonly diamond_helmet: ItemArmor;
	readonly diamond_chestplate: ItemArmor;
	readonly diamond_leggings: ItemArmor;
	readonly diamond_boots: ItemArmor;
	readonly iron_helmet: ItemArmor;
	readonly iron_chestplate: ItemArmor;
	readonly iron_leggings: ItemArmor;
	readonly iron_boots: ItemArmor;
	readonly chainmail_helmet: ItemArmor;
	readonly chainmail_chestplate: ItemArmor;
	readonly chainmail_leggings: ItemArmor;
	readonly chainmail_boots: ItemArmor;
	readonly diamond_pickaxe: ItemPickaxe;
	readonly iron_pickaxe: ItemPickaxe;
	readonly stone_pickaxe: ItemPickaxe;
	readonly wooden_pickaxe: ItemPickaxe;
	readonly ender_pearl: Item;
	readonly snowball: Item;
	readonly egg: Item;
	readonly flint_and_steel: Item;
	readonly fire_charge: Item;
	readonly stone: Item;
	readonly granite: Item;
	readonly polished_granite: Item;
	readonly diorite: Item;
	readonly polished_diorite: Item;
	readonly andesite: Item;
	readonly polished_andesite: Item;
	readonly grass_block: Item;
	readonly dirt: Item;
	readonly coarse_dirt: Item;
	readonly podzol: Item;
	readonly dirt_path: Item;
	readonly cobblestone: Item;
	readonly oak_planks: Item;
	readonly spruce_planks: Item;
	readonly birch_planks: Item;
	readonly jungle_planks: Item;
	readonly acacia_planks: Item;
	readonly dark_oak_planks: Item;
	readonly oak_sapling: Item;
	readonly spruce_sapling: Item;
	readonly birch_sapling: Item;
	readonly jungle_sapling: Item;
	readonly acacia_sapling: Item;
	readonly dark_oak_sapling: Item;
	readonly bedrock: Item;
	readonly sand: Item;
	readonly red_sand: Item;
	readonly gravel: Item;
	readonly gold_ore: Item;
	readonly iron_ore: Item;
	readonly coal_ore: Item;
	readonly diamond_ore: Item;
	readonly emerald_ore: Item;
	readonly lapis_ore: Item;
	readonly redstone_ore: Item;
	readonly hell_marble_ore: Item;
	readonly infernium_ore: Item;
	readonly oak_log: Item;
	readonly spruce_log: Item;
	readonly birch_log: Item;
	readonly jungle_log: Item;
	readonly acacia_log: Item;
	readonly dark_oak_log: Item;
	readonly stripped_oak_log: Item;
	readonly stripped_spruce_log: Item;
	readonly stripped_birch_log: Item;
	readonly stripped_jungle_log: Item;
	readonly stripped_acacia_log: Item;
	readonly stripped_dark_oak_log: Item;
	readonly stripped_oak_wood: Item;
	readonly stripped_spruce_wood: Item;
	readonly stripped_birch_wood: Item;
	readonly stripped_jungle_wood: Item;
	readonly stripped_acacia_wood: Item;
	readonly stripped_dark_oak_wood: Item;
	readonly oak_wood: Item;
	readonly spruce_wood: Item;
	readonly birch_wood: Item;
	readonly jungle_wood: Item;
	readonly acacia_wood: Item;
	readonly dark_oak_wood: Item;
	readonly oak_leaves: Item;
	readonly spruce_leaves: Item;
	readonly birch_leaves: Item;
	readonly jungle_leaves: Item;
	readonly acacia_leaves: Item;
	readonly dark_oak_leaves: Item;
	readonly sponge: Item;
	readonly glass: Item;
	readonly white_stained_glass: Item;
	readonly orange_stained_glass: Item;
	readonly magenta_stained_glass: Item;
	readonly light_blue_stained_glass: Item;
	readonly yellow_stained_glass: Item;
	readonly lime_stained_glass: Item;
	readonly pink_stained_glass: Item;
	readonly gray_stained_glass: Item;
	readonly light_gray_stained_glass: Item;
	readonly cyan_stained_glass: Item;
	readonly purple_stained_glass: Item;
	readonly blue_stained_glass: Item;
	readonly brown_stained_glass: Item;
	readonly green_stained_glass: Item;
	readonly red_stained_glass: Item;
	readonly black_stained_glass: Item;
	readonly coal_block: Item;
	readonly iron_block: Item;
	readonly gold_block: Item;
	readonly diamond_block: Item;
	readonly emerald_block: Item;
	readonly infernium_block: Item;
	readonly lapis_block: Item;
	readonly redstone_block: Item;
	readonly marble_block: Item;
	readonly marble_pillar: Item;
	readonly chiseled_marble_block: Item;
	readonly smooth_marble: Item;
	readonly sandstone: Item;
	readonly chiseled_sandstone: Item;
	readonly smooth_sandstone: Item;
	readonly cut_sandstone: Item;
	readonly red_sandstone: Item;
	readonly chiseled_red_sandstone: Item;
	readonly smooth_red_sandstone: Item;
	readonly cut_red_sandstone: Item;
	readonly note_block: Item;
	readonly bookshelf: Item;
	readonly workbench: Item;
	readonly bricks: Item;
	readonly tnt: Item;
	readonly mossy_cobblestone: Item;
	readonly obsidian: Item;
	readonly cake: Item;
	readonly cobweb: Item;
	readonly furnace: Item;
	readonly grass: Item;
	readonly dead_bush: Item;
	readonly fern: Item;
	readonly white_wool: Item;
	readonly orange_wool: Item;
	readonly magenta_wool: Item;
	readonly light_blue_wool: Item;
	readonly yellow_wool: Item;
	readonly lime_wool: Item;
	readonly pink_wool: Item;
	readonly gray_wool: Item;
	readonly light_gray_wool: Item;
	readonly cyan_wool: Item;
	readonly purple_wool: Item;
	readonly blue_wool: Item;
	readonly brown_wool: Item;
	readonly green_wool: Item;
	readonly red_wool: Item;
	readonly black_wool: Item;
	readonly poppy: Item;
	readonly dandelion: Item;
	readonly blue_orchid: Item;
	readonly allium: Item;
	readonly azure_bluet: Item;
	readonly red_tulip: Item;
	readonly orange_tulip: Item;
	readonly white_tulip: Item;
	readonly pink_tulip: Item;
	readonly oxeye_daisy: Item;
	readonly red_mushroom: Item;
	readonly brown_mushroom: Item;
	readonly ice: Item;
	readonly packed_ice: Item;
	readonly snow_block: Item;
	readonly clay: Item;
	readonly jukebox: Item;
	readonly pumpkin: Item;
	readonly carved_pumpkin: Item;
	readonly jack_o_lantern: Item;
	readonly hellstone: Item;
	readonly soul_sand: Item;
	readonly glowstone: Item;
	readonly melon: Item;
	readonly slime_block: Item;
	readonly hay_block: Item;
	readonly terracotta: Item;
	readonly white_terracotta: Item;
	readonly orange_terracotta: Item;
	readonly magenta_terracotta: Item;
	readonly light_blue_terracotta: Item;
	readonly yellow_terracotta: Item;
	readonly lime_terracotta: Item;
	readonly pink_terracotta: Item;
	readonly gray_terracotta: Item;
	readonly light_gray_terracotta: Item;
	readonly cyan_terracotta: Item;
	readonly purple_terracotta: Item;
	readonly blue_terracotta: Item;
	readonly brown_terracotta: Item;
	readonly green_terracotta: Item;
	readonly red_terracotta: Item;
	readonly black_terracotta: Item;
	readonly white_concrete: Item;
	readonly orange_concrete: Item;
	readonly magenta_concrete: Item;
	readonly light_blue_concrete: Item;
	readonly yellow_concrete: Item;
	readonly lime_concrete: Item;
	readonly pink_concrete: Item;
	readonly gray_concrete: Item;
	readonly light_gray_concrete: Item;
	readonly cyan_concrete: Item;
	readonly purple_concrete: Item;
	readonly blue_concrete: Item;
	readonly brown_concrete: Item;
	readonly green_concrete: Item;
	readonly red_concrete: Item;
	readonly black_concrete: Item;
	readonly stone_bricks: Item;
	readonly smooth_stone: Item;
	readonly mossy_stone_bricks: Item;
	readonly cracked_stone_bricks: Item;
	readonly chiseled_stone_bricks: Item;
	readonly brown_mushroom_block: Item;
	readonly red_mushroom_block: Item;
	readonly mushroom_stem: Item;
	readonly hell_bricks: Item;
	readonly hell_fungus_block: Item;
	readonly red_hell_bricks: Item;
	readonly chiseled_hell_bricks: Item;
	readonly cracked_hell_bricks: Item;
	readonly marble_bricks: Item;
	readonly aquastone: Item;
	readonly aquastone_bricks: Item;
	readonly dark_aquastone: Item;
	readonly end_stone: Item;
	readonly end_stone_bricks: Item;
	readonly oak_stairs: Item;
	readonly spruce_stairs: Item;
	readonly birch_stairs: Item;
	readonly jungle_stairs: Item;
	readonly acacia_stairs: Item;
	readonly dark_oak_stairs: Item;
	readonly stone_stairs: Item;
	readonly cobblestone_stairs: Item;
	readonly brick_stairs: Item;
	readonly stone_brick_stairs: Item;
	readonly hell_brick_stairs: Item;
	readonly sandstone_stairs: Item;
	readonly smooth_sandstone_stairs: Item;
	readonly red_sandstone_stairs: Item;
	readonly smooth_red_sandstone_stairs: Item;
	readonly marble_stairs: Item;
	readonly smooth_marble_stairs: Item;
	readonly andesite_stairs: Item;
	readonly diorite_stairs: Item;
	readonly granite_stairs: Item;
	readonly polished_andesite_stairs: Item;
	readonly polished_diorite_stairs: Item;
	readonly polished_granite_stairs: Item;
	readonly end_stone_brick_stairs: Item;
	readonly aquastone_stairs: Item;
	readonly aquastone_brick_stairs: Item;
	readonly dark_aquastone_stairs: Item;
	readonly mossy_cobblestone_stairs: Item;
	readonly mossy_stone_brick_stairs: Item;
	readonly purpur_stairs: Item;
	readonly red_hell_brick_stairs: Item;
	readonly blackstone_stairs: Item;
	readonly polished_blackstone_stairs: Item;
	readonly polished_blackstone_brick_stairs: Item;
	readonly crimson_stairs: Item;
	readonly warped_stairs: Item;
	readonly cactus: Item;
	readonly ladder: Item;
	readonly iron_ladder: Item;
	readonly vine: Item;
	readonly sea_lantern: Item;
	readonly command_block: Item;
	readonly white_carpet: Item;
	readonly orange_carpet: Item;
	readonly magenta_carpet: Item;
	readonly light_blue_carpet: Item;
	readonly yellow_carpet: Item;
	readonly lime_carpet: Item;
	readonly pink_carpet: Item;
	readonly gray_carpet: Item;
	readonly light_gray_carpet: Item;
	readonly cyan_carpet: Item;
	readonly purple_carpet: Item;
	readonly blue_carpet: Item;
	readonly brown_carpet: Item;
	readonly green_carpet: Item;
	readonly red_carpet: Item;
	readonly black_carpet: Item;
	readonly muck: Item;
	readonly snow: Item;
	readonly enchanting_table: Item;
	readonly chest: Item;
	readonly ender_chest: Item;
	readonly barrel: Item;
	readonly sticky_piston: Item;
	readonly piston: Item;
	readonly barrier: Item;
	readonly lever: Item;
	readonly stone_button: Item;
	readonly oak_button: Item;
	readonly spruce_button: Item;
	readonly birch_button: Item;
	readonly jungle_button: Item;
	readonly acacia_button: Item;
	readonly dark_oak_button: Item;
	readonly crimson_button: Item;
	readonly warped_button: Item;
	readonly polished_blackstone_button: Item;
	readonly repeater: Item;
	readonly comparator: Item;
	readonly redstone_lamp: Item;
	readonly observer: Item;
	readonly target: Item;
	readonly stone_pressure_plate: Item;
	readonly oak_pressure_plate: Item;
	readonly spruce_pressure_plate: Item;
	readonly birch_pressure_plate: Item;
	readonly jungle_pressure_plate: Item;
	readonly acacia_pressure_plate: Item;
	readonly dark_oak_pressure_plate: Item;
	readonly crimson_pressure_plate: Item;
	readonly warped_pressure_plate: Item;
	readonly polished_blackstone_pressure_plate: Item;
	readonly light_weighted_pressure_plate: Item;
	readonly heavy_weighted_pressure_plate: Item;
	readonly oak_fence: Item;
	readonly spruce_fence: Item;
	readonly birch_fence: Item;
	readonly jungle_fence: Item;
	readonly acacia_fence: Item;
	readonly dark_oak_fence: Item;
	readonly hell_brick_fence: Item;
	readonly crimson_fence: Item;
	readonly warped_fence: Item;
	readonly oak_fence_gate: Item;
	readonly spruce_fence_gate: Item;
	readonly birch_fence_gate: Item;
	readonly jungle_fence_gate: Item;
	readonly acacia_fence_gate: Item;
	readonly dark_oak_fence_gate: Item;
	readonly crimson_fence_gate: Item;
	readonly warped_fence_gate: Item;
	readonly andesite_wall: Item;
	readonly blackstone_wall: Item;
	readonly polished_blackstone_wall: Item;
	readonly polished_blackstone_brick_wall: Item;
	readonly brick_wall: Item;
	readonly cobblestone_wall: Item;
	readonly diorite_wall: Item;
	readonly end_stone_brick_wall: Item;
	readonly granite_wall: Item;
	readonly mossy_cobblestone_wall: Item;
	readonly mossy_stone_brick_wall: Item;
	readonly hell_brick_wall: Item;
	readonly red_hell_brick_wall: Item;
	readonly sandstone_wall: Item;
	readonly stone_brick_wall: Item;
	readonly red_sandstone_wall: Item;
	readonly aquastone_wall: Item;
	readonly iron_bars: Item;
	readonly glass_pane: Item;
	readonly white_stained_glass_pane: Item;
	readonly orange_stained_glass_pane: Item;
	readonly magenta_stained_glass_pane: Item;
	readonly light_blue_stained_glass_pane: Item;
	readonly yellow_stained_glass_pane: Item;
	readonly lime_stained_glass_pane: Item;
	readonly pink_stained_glass_pane: Item;
	readonly gray_stained_glass_pane: Item;
	readonly light_gray_stained_glass_pane: Item;
	readonly cyan_stained_glass_pane: Item;
	readonly purple_stained_glass_pane: Item;
	readonly blue_stained_glass_pane: Item;
	readonly brown_stained_glass_pane: Item;
	readonly green_stained_glass_pane: Item;
	readonly red_stained_glass_pane: Item;
	readonly black_stained_glass_pane: Item;
	readonly brewing_stand: Item;
	readonly cauldron: Item;
	readonly oak_trapdoor: Item;
	readonly spruce_trapdoor: Item;
	readonly birch_trapdoor: Item;
	readonly jungle_trapdoor: Item;
	readonly acacia_trapdoor: Item;
	readonly dark_oak_trapdoor: Item;
	readonly iron_trapdoor: Item;
	readonly dragon_egg: Item;
	readonly anvil: Item;
	readonly dispenser: Item;
	readonly dropper: Item;
	readonly hopper: Item;
	readonly white_bed: Item;
	readonly orange_bed: Item;
	readonly magenta_bed: Item;
	readonly light_blue_bed: Item;
	readonly yellow_bed: Item;
	readonly lime_bed: Item;
	readonly pink_bed: Item;
	readonly gray_bed: Item;
	readonly light_gray_bed: Item;
	readonly cyan_bed: Item;
	readonly purple_bed: Item;
	readonly blue_bed: Item;
	readonly brown_bed: Item;
	readonly green_bed: Item;
	readonly red_bed: Item;
	readonly black_bed: Item;
	readonly sugar_cane: Item;
	readonly bone_block: Item;
	readonly cloud_block: Item;
	readonly blackstone: Item;
	readonly polished_blackstone: Item;
	readonly polished_blackstone_bricks: Item;
	readonly cracked_polished_blackstone_bricks: Item;
	readonly chiseled_polished_blackstone: Item;
	readonly gilded_blackstone: Item;
	readonly basalt: Item;
	readonly polished_basalt: Item;
	readonly soul_soil: Item;
	readonly crying_obsidian: Item;
	readonly magma_block: Item;
	readonly campfire: Item;
	readonly soul_campfire: Item;
	readonly lantern: Item;
	readonly soul_lantern: Item;
	readonly shroomlight: Item;
	readonly lodestone: Item;
	readonly hell_gold_ore: Item;
	readonly crimson_stem: Item;
	readonly warped_stem: Item;
	readonly stripped_crimson_stem: Item;
	readonly stripped_warped_stem: Item;
	readonly crimson_hyphae: Item;
	readonly warped_hyphae: Item;
	readonly stripped_crimson_hyphae: Item;
	readonly stripped_warped_hyphae: Item;
	readonly crimson_planks: Item;
	readonly warped_planks: Item;
	readonly crimson_nylium: Item;
	readonly warped_nylium: Item;
	readonly warped_wart_block: Item;
	readonly crimson_fungus: Item;
	readonly warped_fungus: Item;
	readonly crimson_roots: Item;
	readonly warped_roots: Item;
	readonly hell_sprouts: Item;
	readonly crimson_trapdoor: Item;
	readonly warped_trapdoor: Item;
	readonly purpur_block: Item;
	readonly purpur_pillar: Item;
	readonly meteorite_block: Item;
	readonly wet_sponge: Item;
	readonly honeycomb_block: Item;
	readonly honey_block: Item;
	readonly blue_ice: Item;
	readonly white_glazed_terracotta: Item;
	readonly orange_glazed_terracotta: Item;
	readonly magenta_glazed_terracotta: Item;
	readonly light_blue_glazed_terracotta: Item;
	readonly yellow_glazed_terracotta: Item;
	readonly lime_glazed_terracotta: Item;
	readonly pink_glazed_terracotta: Item;
	readonly gray_glazed_terracotta: Item;
	readonly light_gray_glazed_terracotta: Item;
	readonly cyan_glazed_terracotta: Item;
	readonly purple_glazed_terracotta: Item;
	readonly blue_glazed_terracotta: Item;
	readonly brown_glazed_terracotta: Item;
	readonly green_glazed_terracotta: Item;
	readonly red_glazed_terracotta: Item;
	readonly black_glazed_terracotta: Item;
	readonly white_concrete_powder: Item;
	readonly orange_concrete_powder: Item;
	readonly magenta_concrete_powder: Item;
	readonly light_blue_concrete_powder: Item;
	readonly yellow_concrete_powder: Item;
	readonly lime_concrete_powder: Item;
	readonly pink_concrete_powder: Item;
	readonly gray_concrete_powder: Item;
	readonly light_gray_concrete_powder: Item;
	readonly cyan_concrete_powder: Item;
	readonly purple_concrete_powder: Item;
	readonly blue_concrete_powder: Item;
	readonly brown_concrete_powder: Item;
	readonly green_concrete_powder: Item;
	readonly red_concrete_powder: Item;
	readonly black_concrete_powder: Item;
	readonly cornflower: Item;
	readonly lily_of_the_valley: Item;
	readonly wither_rose: Item;
	readonly sunflower: Item;
	readonly lilac: Item;
	readonly rose_bush: Item;
	readonly peony: Item;
	readonly tall_grass: Item;
	readonly large_fern: Item;
	readonly repeating_command_block: Item;
	readonly chain_command_block: Item;
	readonly chipped_anvil: Item;
	readonly damaged_anvil: Item;
	readonly rail: Item;
	readonly powered_rail: Item;
	readonly detector_rail: Item;
	readonly activator_rail: Item;
	readonly spawner: Item;
	readonly flower_pot: Item;
	readonly wooden_shovel: Item;
	readonly wooden_axe: Item;
	readonly wooden_hoe: Item;
	readonly stone_shovel: Item;
	readonly stone_axe: Item;
	readonly stone_hoe: Item;
	readonly iron_shovel: Item;
	readonly iron_axe: Item;
	readonly iron_hoe: Item;
	readonly golden_shovel: Item;
	readonly golden_pickaxe: Item;
	readonly golden_axe: Item;
	readonly golden_sword: Item;
	readonly golden_hoe: Item;
	readonly diamond_shovel: Item;
	readonly diamond_axe: Item;
	readonly diamond_hoe: Item;
	readonly emerald_shovel: Item;
	readonly emerald_pickaxe: Item;
	readonly emerald_axe: Item;
	readonly emerald_hoe: Item;
	readonly infernium_pickaxe: Item;
	readonly infernium_axe: Item;
	readonly infernium_sword: Item;
	readonly mace: Item;
	readonly wooden_spear: Item;
	readonly stone_spear: Item;
	readonly iron_spear: Item;
	readonly golden_spear: Item;
	readonly diamond_spear: Item;
	readonly infernium_spear: Item;
	readonly baked_potato: Item;
	readonly beef: Item;
	readonly beetroot: Item;
	readonly beetroot_soup: Item;
	readonly carrot: Item;
	readonly chicken: Item;
	readonly cod: Item;
	readonly cooked_chicken: Item;
	readonly cooked_cod: Item;
	readonly cooked_mutton: Item;
	readonly cooked_rabbit: Item;
	readonly cookie: Item;
	readonly dried_kelp: Item;
	readonly golden_carrot: Item;
	readonly honey_bottle: Item;
	readonly melon_slice: Item;
	readonly mushroom_stew: Item;
	readonly mutton: Item;
	readonly poisonous_potato: Item;
	readonly porkchop: Item;
	readonly potato: Item;
	readonly pufferfish: Item;
	readonly pumpkin_pie: Item;
	readonly rabbit: Item;
	readonly rabbit_stew: Item;
	readonly rotten_flesh: Item;
	readonly salmon: Item;
	readonly cooked_salmon: Item;
	readonly spider_eye: Item;
	readonly tropical_fish: Item;
	readonly orange: Item;
	readonly banana: Item;
	readonly enchanted_golden_apple: Item;
	readonly potion: Item;
	readonly fishing_rod: Item;
	readonly tipped_arrow: Item;
	readonly spectral_arrow: Item;
	readonly iron_ingot: Item;
	readonly iron_nugget: Item;
	readonly gold_ingot: Item;
	readonly gold_nugget: Item;
	readonly lapis_lazuli: Item;
	readonly coal: Item;
	readonly charcoal: Item;
	readonly diamond: Item;
	readonly emerald: Item;
	readonly redstone: Item;
	readonly infernium_ingot: Item;
	readonly stick: Item;
	readonly book: Item;
	readonly writable_book: Item;
	readonly written_book: Item;
	readonly enchanted_book: Item;
	readonly string: Item;
	readonly slime_ball: Item;
	readonly shears: Item;
	readonly leather_helmet: Item;
	readonly leather_chestplate: Item;
	readonly leather_leggings: Item;
	readonly leather_boots: Item;
	readonly golden_helmet: Item;
	readonly golden_chestplate: Item;
	readonly golden_leggings: Item;
	readonly golden_boots: Item;
	readonly emerald_helmet: Item;
	readonly emerald_chestplate: Item;
	readonly emerald_leggings: Item;
	readonly emerald_boots: Item;
	readonly infernium_helmet: Item;
	readonly infernium_chestplate: Item;
	readonly infernium_leggings: Item;
	readonly infernium_boots: Item;
	readonly stone_slab: Item;
	readonly stone_brick_slab: Item;
	readonly smooth_stone_slab: Item;
	readonly marble_slab: Item;
	readonly oak_slab: Item;
	readonly spruce_slab: Item;
	readonly birch_slab: Item;
	readonly jungle_slab: Item;
	readonly acacia_slab: Item;
	readonly dark_oak_slab: Item;
	readonly cobblestone_slab: Item;
	readonly brick_slab: Item;
	readonly sandstone_slab: Item;
	readonly red_sandstone_slab: Item;
	readonly granite_slab: Item;
	readonly diorite_slab: Item;
	readonly andesite_slab: Item;
	readonly polished_granite_slab: Item;
	readonly polished_diorite_slab: Item;
	readonly polished_andesite_slab: Item;
	readonly mossy_stone_brick_slab: Item;
	readonly mossy_cobblestone_slab: Item;
	readonly end_stone_brick_slab: Item;
	readonly smooth_sandstone_slab: Item;
	readonly smooth_red_sandstone_slab: Item;
	readonly cut_sandstone_slab: Item;
	readonly cut_red_sandstone_slab: Item;
	readonly smooth_marble_slab: Item;
	readonly hell_brick_slab: Item;
	readonly red_hell_brick_slab: Item;
	readonly purpur_slab: Item;
	readonly aquastone_slab: Item;
	readonly aquastone_brick_slab: Item;
	readonly dark_aquastone_slab: Item;
	readonly blackstone_slab: Item;
	readonly polished_blackstone_slab: Item;
	readonly polished_blackstone_brick_slab: Item;
	readonly crimson_slab: Item;
	readonly warped_slab: Item;
	readonly oak_door: Item;
	readonly iron_door: Item;
	readonly spruce_door: Item;
	readonly birch_door: Item;
	readonly jungle_door: Item;
	readonly acacia_door: Item;
	readonly dark_oak_door: Item;
	readonly crimson_door: Item;
	readonly warped_door: Item;
	readonly bucket: Item;
	readonly water_bucket: Item;
	readonly lava_bucket: Item;
	readonly cod_bucket: Item;
	readonly salmon_bucket: Item;
	readonly pufferfish_bucket: Item;
	readonly tropical_fish_bucket: Item;
	readonly paper: Item;
	readonly unknown_item: Item;
	readonly leather: Item;
	readonly hell_brick: Item;
	readonly blaze_rod: Item;
	readonly blaze_powder: Item;
	readonly magma_cream: Item;
	readonly glowstone_dust: Item;
	readonly fermented_spider_eye: Item;
	readonly glistering_melon_slice: Item;
	readonly nether_wart: Item;
	readonly rabbit_foot: Item;
	readonly feather: Item;
	readonly flint: Item;
	readonly wheat_seeds: Item;
	readonly pumpkin_seeds: Item;
	readonly melon_seeds: Item;
	readonly beetroot_seeds: Item;
	readonly wheat: Item;
	readonly bowl: Item;
	readonly gunpowder: Item;
	readonly acacia_sign: Item;
	readonly birch_sign: Item;
	readonly dark_oak_sign: Item;
	readonly jungle_sign: Item;
	readonly oak_sign: Item;
	readonly spruce_sign: Item;
	readonly player_head: Item;
	readonly white_dye: Item;
	readonly orange_dye: Item;
	readonly magenta_dye: Item;
	readonly light_blue_dye: Item;
	readonly yellow_dye: Item;
	readonly lime_dye: Item;
	readonly pink_dye: Item;
	readonly gray_dye: Item;
	readonly light_gray_dye: Item;
	readonly cyan_dye: Item;
	readonly purple_dye: Item;
	readonly blue_dye: Item;
	readonly brown_dye: Item;
	readonly green_dye: Item;
	readonly red_dye: Item;
	readonly black_dye: Item;
	readonly bone: Item;
	readonly sugar: Item;
	readonly bone_meal: Item;
	readonly cocoa_beans: Item;
	readonly hell_star: Item;
	readonly brick: Item;
	readonly clay_ball: Item;
	readonly torch: Item;
	readonly soul_torch: Item;
	readonly redstone_torch: Item;
	readonly glass_bottle: Item;
	readonly lily_pad: Item;
	readonly marble: Item;
	readonly elytra: Item;
	readonly firework_rocket: Item;
	readonly experience_bottle: Item;
	readonly acacia_boat: Item;
	readonly birch_boat: Item;
	readonly dark_oak_boat: Item;
	readonly jungle_boat: Item;
	readonly oak_boat: Item;
	readonly spruce_boat: Item;
	readonly minecart: Item;
	readonly item_frame: Item;
	readonly armor_stand: Item;
	readonly milk_bucket: Item;
	readonly name_tag: Item;
	readonly pig_spawn_egg: Item;
	readonly cow_spawn_egg: Item;
	readonly chicken_spawn_egg: Item;
	readonly sheep_spawn_egg: Item;
	readonly wolf_spawn_egg: Item;
	readonly cat_spawn_egg: Item;
	readonly zombie_spawn_egg: Item;
	readonly skeleton_spawn_egg: Item;
	readonly creeper_spawn_egg: Item;
	readonly slime_spawn_egg: Item;
	readonly spider_spawn_egg: Item;
	readonly villager_spawn_egg: Item;
	readonly clock: Item;
	readonly compass: Item;
	readonly ghost_tear: Item;
	// Add more items as needed
	[key: string]: Item;
};
