import type { Vector3 } from "three";
import type { Block, BlockChest } from "../blocks";
import type { Container, ContainerPlayer } from "../container";
import type { Abilities, GameMode } from "../game/gamemode";
import type { Team } from "../game/team";
import type { Game } from "../game";
import type { InventoryPlayer } from "../inventory";
import type { ItemStack } from "../items";
import type { EnumFacing } from "../math/facing";
import type { SPacketPlayerInput } from "../packets";
import type {
	FoodStats,
	GameProfile,
	InventoryEnderChest,
	Profile,
	TileEntitySign,
} from "../undefined";
import type { World } from "../world";
import type { BlockPos } from "../world/blockpos";
import type { Entity } from "./Entity";
import type { EntityLivingBase } from "./EntityLivingBase";

export declare interface IInterface {
	getGuiID(): string;
}

export declare class EntityPlayer extends EntityLivingBase {
	mode: GameMode;
	inventory: InventoryPlayer;
	inventoryEnderChest: InventoryEnderChest;
	abilities: Abilities;
	inventoryContainer: ContainerPlayer;
	openContainer: Container;
	punching: boolean;
	flySpeed: number;
	speedInAir: number;
	name: string;
	foodStats: FoodStats;
	actualName: string;
	experienceLevel: number;
	experienceTotal: number;
	experience: number;
	xpSeed: number;
	xpCooldown: number;
	xpInitialized: boolean;
	itemInUse: ItemStack | null;
	itemInUseCount: number;
	type: string;
	identifier: number;
	sleeping: boolean;
	sleepTimer: number;
	spawnChunk: unknown;
	spawnForced: boolean | undefined;
	profile: GameProfile;
	prevInventory: Inventory;
	prevDefencePoints: number;
	game: Game;
	positionUpdateTicks: number;
	lastjump: number;
	lastItemUseTime: number;
	bareName: string;
	namePrefix: string;
	homes: unknown;
	guideProgress: unknown;
	itemInUseHand: number;
	itemInUseSlot: number;
	pendingUseHand: number;
	sentInputThisTick: boolean;
	elytraDescentSpeed: number;
	elytraFallGraceTicks: number;
	elytraWasJumping: boolean;
	fireworkBoostTicks: number;
	maceSmashNoFallUntil: number;
	emote: number;
	emoteStartMs: number;
	emoteMoveLatch: boolean;
	emoteCameraAutoSwitched: boolean;
	spectateCamAttached: boolean;
	spectateCamPitch: number;
	spectateCamPos: unknown;
	spectateCamYaw: number;
	spectateSavedHeldSlot: unknown | null;
	spectateStream: unknown;
	spectatingEntityId: number | null;
	deathCameraActive: boolean;
	deathCamFocus: unknown;
	deathCamPos: unknown;
	deathPrevPerspective: number;
	deathSpot: unknown;
	deathYaw: number;
	lastChargeHitAt: number;
	lastJabAt: number;
	lastLungeAt: number;
	lowHealthPulse: unknown | null;
	recentFallDamage: number;
	recentFallDistance: number;
	recentFallLandAt: number;
	predictedStates: unknown;
	lastServerAckId: number;
	teamColorApplied: boolean;
	fishEntity: Entity | null;
	previousEquipment: unknown[];
	perspective: number;
	deltaFov: unknown;
	portalTint: unknown;
	oxygen: number;
	selectBox: unknown;
	headInBlock: Block | null;
	lastHeadInBlock: Block | null;
	biome: string;
	lastReportedPos: Vector3;
	/** IMPORTANT: USE DUMPS */
	lastReportedYaw: number;
	lastReportedPitch: number | undefined;
	serverSneakState: boolean;
	serverSprintState: boolean;
	serverPunchState: boolean;
	serverBlockState: boolean;
	serverFlyState: boolean;
	serverMoveStrafe: number;
	serverMoveForward: number;
	serverDistance: number;
	currentInput: SPacketPlayerInput | null;
	inputSequenceNumber: number;
	pendingInputs: SPacketPlayerInput[];
	flyToggleTimer: number;
	sprintToggleTimer: number;
	sprintingTicksLeft: number;
	sprintKeyWasDown: boolean;
	showDeathScreen: boolean;
	currentTile: BlockPos;
	constructor(profile: Profile, world: World);
	isAdmin(): boolean;
	isUsingItem(): boolean;
	isBlocking(): boolean;
	getHorizontalDirection(): EnumFacing;
	getEyeHeight(): number;
	canPlayerEdit(_?: unknown, __?: unknown, ___?: unknown): boolean;
	getActiveItemStack(): ItemStack;
	getEquipmentInSlot(h: unknown): unknown;
	onDeath(attackingPlayer: EntityPlayer): void;
	isSprinting(): boolean;
	/** IMPORTANT: USE DUMPS */
	attack(e: EntityLivingBase): void;
	addStat(h: unknown, p: unknown): void;
	addMovementStat(h: unknown, p: unknown, g: unknown): void;
	updateItemInUse(): void;
	getExperiencePoints(_unused?: EntityPlayer): number;
	addExperience(xp: number): void;
	setExperience(h: unknown, p: unknown): void;
	xpBarCap(): number;
	removeExperienceLevel(h: unknown): void;
	addExperienceLevel(h: unknown): void;
	update(): void;
	setCurrentItemOrArmor(h: unknown, p: unknown): void;
	preparePlayerToSpawn(): void;
	setGamemode(gameMode: GameMode): boolean;
	displayGUIChest(chest: BlockChest): void;
	displayGui(h: IInterface): void;
	openEditSign(sign: TileEntitySign): void;
	closeScreen(): void;
	dropItem(h: unknown, p: unknown, g: unknown, y?: boolean): unknown;
	joinEntityItemWithWorld(e: Entity): void;
	canHarvestBlock(h: Block): boolean;
	addExhaustion(h: unknown): void;
	getFoodStats(): FoodStats;
	setItemInUse(h: unknown, p: unknown): void;
	onItemUseFinish(): void;
	handleStatusUpdate(h: unknown): void;
	setAbsorptionAmount(h: unknown): void;
	sendMessage(h: unknown, p: unknown): void;
	isPlayerSleeping(): boolean;
	isSpectator(): boolean;
	interactFirst(h: unknown): boolean;
	onTeamChanged(): void;
	checkCollisionWithEntities(): void;
	getOffhandItem(): ItemStack | null;
	setUsingOffHand(using: boolean): void;
	swapHandItems(): void;
	isElytraFlying(): boolean;
	isSpearCharging(): boolean;
	trySpearLunge(): void;
	chargeAttackEntity(): void;
	addLungeVelocity(): void;
	checkTotemDeathProtection(): boolean;
	tickEquipmentAbility(): void;
	openBook(): void;
	displayVillagerTradeGui(h: unknown): void;
	getSoundInfo(): unknown;
	getEquippedChestStack(): ItemStack | null;
	getArmorStacks(): ItemStack[];
	getUseHand(): number;
	toggleCameraPerspective(): void;
	beginDeathCamera(): void;
	endDeathCamera(): void;
	renderDeathCamera(): void;
	beginEmoteLocally(): void;
	endEmoteLocally(): void;
	tickLocalEmote(): void;
	applyServerEmote(): void;
	startSpectating(entityId: number): void;
	stopSpectating(): void;
	spectateTargetEntity(): void;
	pushSpectateSample(): void;
	isSpectatingOtherPlayer(): boolean;
	updateModGauge(): void;
	trackImpactLanding(): void;
	sendRespawnPacket(): void;
	dropPlayerItemWithRandomChoice(h: unknown, p?: boolean): unknown;
	openShop(): void;
	hasDaylightSky(): boolean;
	isWallExempt(): boolean;
	serverUsesInputMovement(): boolean;
	serverUsesPosLookMovement(): boolean;
	fixedUpdate(): void;
}

export { EntityPlayer, IInterface };
